version: '3.8'

services:
  mongodb-part2:
    image: mongo:latest
    container_name: opalumpus_mongo_v2   # NEW container name
    ports:
      - "27018:27017"                    # NEW port number (was 27017)
    restart: always

  backend-part2:
    image: node:20-alpine                # Using base image directly (No Dockerfile)
    container_name: opalumpus_backend_v2 # NEW container name
    working_dir: /app
    volumes:
      - ./Backend:/app                   # ATTACHING VOLUME for code

    environment:                                          
      - MONGO_URI=mongodb://mongodb-part2:27017/opalumpus
    
    ports:
      - "5005:5000"                      # NEW port number (was 5000)
    command: sh -c "npm install && npm start"
    depends_on:
      - mongodb-part2

  frontend-part2:
    image: node:20-alpine                # Using base image directly (No Dockerfile)
    container_name: opalumpus_frontend_v2 # NEW container name
    working_dir: /app
    volumes:
      - ./Opalumpus_frontEnd:/app        # ATTACHING VOLUME for code
    ports:
      - "5174:5173"                      # NEW port number (was 5173)
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend-part2
